// Command golower writes src/core/go_lower_table.rs: every code point
// Go's strings.ToLower changes, with what it changes it to. facetql's
// predicate `lower` must answer as the fct language's `lower` (Go's
// strings.ToLower) does, character for character, whatever Unicode version
// Rust's own tables are at — so it reads Go's mapping, not Rust's.
//
//	go run ./tools/golower > src/core/go_lower_table.rs
package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"unicode"
)

func main() {
	w := bufio.NewWriter(os.Stdout)
	defer w.Flush()
	fmt.Fprintln(w, "// Generated by tools/golower (go run ./tools/golower > src/core/go_lower_table.rs).")
	fmt.Fprintf(w, "// Go's strings.ToLower, Unicode %s: every code point it changes, and its lowercase.\n", unicode.Version)
	fmt.Fprintln(w, "// Do not edit; regenerate.")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "pub const GO_UNICODE_VERSION: &str = %q;\n\n", unicode.Version)
	fmt.Fprintln(w, "pub const GO_LOWER: &[(char, char)] = &[")
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if r >= 0xD800 && r <= 0xDFFF {
			continue
		}
		l := []rune(strings.ToLower(string(r)))
		if len(l) != 1 {
			fmt.Fprintf(os.Stderr, "U+%04X lowers to %d code points\n", r, len(l))
			os.Exit(1)
		}
		if l[0] == r {
			continue
		}
		fmt.Fprintf(w, "    ('\\u{%X}', '\\u{%X}'),\n", r, l[0])
	}
	fmt.Fprintln(w, "];")
}
